name = "hugo-ashen-simple-theme"
license = "MIT"
licenselink = "https://github.com/masa0221/hugo-ashen-simple-theme/blob/master/LICENSE.md"
description = "ashen simple is a simple blog theme for hugo"
homepage = "http://2626.info/"
tags = ["blog", "personal"]
features = ["blog"]
min_version = 0.15

[author]
  name = "Masashi Tsuru"
  homepage = "http://2626.info/"
